export const WORD_RADIUS = 500;
export const CONSONANT_RADIUS = 150;
export const VOWEL_RADIUS = 40
export const CUT_CONSONANT_TILT = 1.8
export const CUT_CONSONANT_VOWEL_TILT = 1.34
export const WORD_TILT = 40;
export const VOWEL_TILT = 80;
export const CONSONANT_TYPE_INNER = 1;
export const CONSONANT_TYPE_CROSS = 2;
export const CONSONANT_TYPE_HALF = 3;
export const CONSONANT_TYPE_CUT = 4;
export const CONSONANT_TYPE_CUT_WORD = 5;
export const VOWEL_A = 6;
export const VOWEL_E = 7;
export const VOWEL_I = 8;
export const VOWEL_O = 9;
export const VOWEL_U = 10;


export const  CONSONANT_B = CONSONANT_TYPE_CUT
export const  CONSONANT_C = CONSONANT_TYPE_INNER
export const  CONSONANT_CH = CONSONANT_TYPE_CUT
export const  CONSONANT_D = CONSONANT_TYPE_CUT
export const  CONSONANT_F = CONSONANT_TYPE_CUT
export const  CONSONANT_G = CONSONANT_TYPE_CUT
export const  CONSONANT_H = CONSONANT_TYPE_CUT
export const  CONSONANT_J = CONSONANT_TYPE_INNER
export const  CONSONANT_K = CONSONANT_TYPE_INNER
export const  CONSONANT_L = CONSONANT_TYPE_INNER
export const  CONSONANT_M = CONSONANT_TYPE_INNER
export const  CONSONANT_N = CONSONANT_TYPE_INNER
export const  CONSONANT_P = CONSONANT_TYPE_INNER
export const  CONSONANT_Q = CONSONANT_TYPE_CROSS
export const  CONSONANT_R = CONSONANT_TYPE_HALF
export const  CONSONANT_S = CONSONANT_TYPE_HALF
export const  CONSONANT_SH = CONSONANT_TYPE_HALF
export const  CONSONANT_T = CONSONANT_TYPE_HALF
export const  CONSONANT_TH = CONSONANT_TYPE_CROSS
export const  CONSONANT_V = CONSONANT_TYPE_HALF
export const  CONSONANT_W = CONSONANT_TYPE_HALF
export const  CONSONANT_X = CONSONANT_TYPE_CROSS
export const  CONSONANT_Y = CONSONANT_TYPE_CROSS
export const  CONSONANT_Z = CONSONANT_TYPE_CROSS

export const  MODIFIER_OUT = 11
export const  MODIFIER_INNER = 12
export const  MODIFIER_DOOTS = 13




 